- name: Create storage account
  hosts: localhost
  connection: local
  tasks:
  - name: Create an account with kind of FileStorage
    azure_rm_storageaccount:
      resource_group: PedroTactile
      name: pedrostorage
      type: Standard_LRS
      kind: Storage
  - name: Create storage share
    azure.azcollection.azure_rm_storageshare:
      name: pedroshare
      resource_group: PedroTactile
      account_name: pedrostorage
      state: present
      quota: 5120