- name: Création VM pour y mettre le container
  hosts: localhost
  connection: local
  tasks:

  - name: Création de la VM
    azure_rm_virtualmachine:
      resource_group: PedroTactile
      name: PedroPanel
      vm_size: Standard_B2s
      admin_username: pedro
      ssh_password_enabled: false
      network_interface_names: PedroPanelNIC
      # storage_account_name: pedrostorage
      ssh_public_keys:
      - path: /home/pedro/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpS16kB+yoDsbFdT93X5mfmrd+RYcJ/s8e/r/F8Q0i5mrCruIHPxFfy/Grekq1UZ8OyIRjW1tPg5KD1OC9ahJXWY+jaUCacBsM4c/RfPc4a2mn5oXoAF2YNOra9/3Us1y/Cx0Vq2Ie0Xjs07FqaXvticlroBCZ9c8PRmMBSNmsgTwm+Sbazs9KaPbg/M1XlgscqlG3SX6m9uI5s2FzpeK55jTfmECRWOIwlYmeRrz2h/9h2eKzjaQDxH3zjyoHiTJ2hgCN7ZQhc8DoQ4DBdKt01X6pL/HMnRlg8ojsQPkUxUENu858u25hx/pEFi3AqTDeGBA4Zxup0fVQetkkwSxV"
      image:
        offer: debian-10
        publisher: Debian
        sku: '10'
        version: latest
      custom_data: "{{ lookup('file', '/home/alain/Documents/gitcloneb4/Simplon-Groupe2brief4/PreDroProd/initPanel') }}"